#!/usr/bin/env bash

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Display To infinity and beyond indefinitely
while true; do
    echo "To infinity and beyond"
done

# Display I hate the kill command when receiving a SIGTERM signal
trap "echo 'I hate the kill command'" SIGTERM

# Display Y U no love me?! when receiving a SIGINT signal
trap "echo 'Y U no love me?!'" SIGINT

# Delete the file /var/run/myscript.pid and terminate itself when receiving a SIGQUIT or a SIGTERM signal
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT SIGTERM
